server:
  port: 9001 # 网关端口

spring:
  application:
    name: gateway-service # 服务名称
  cloud:
    nacos:
      server-addr: 1.117.34.49:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: demo-user # 自定义路由id
          uri: lb://demo-user # 路由目标地址 lb是loadbalance的缩写 后面紧跟服务名称
          filters: # 过滤器配置
            - AddRequestParameter=username, user # 请求添加参数, ','前面为key,后面为value
          predicates: # 路由断言：判断请求是否符合路由规则的条件
            - Path=/member/** # 按照路径匹配
      default-filters:
        - AddRequestParameter=username, user
      globalcors: # 全局跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求（浏览器询问服务端是否允许跨域的请求）被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://1.117.34.49:9001"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
